# This is the pipeline that will run nightly

name: Nightly

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '2 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Part A Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TEST_FEATURE: [FeatureA, FeatureB, FeatureC, FeatureD, FeatureE, FeatureF]

    steps:
      - uses: actions/checkout@v3

      - name: ${{ matrix.TEST_FEATURE }}
        run: |
          cd part_a/tests
          ./run.sh ${{ matrix.TEST_FEATURE }} nightly | tee log.txt

      - name: Archive log
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.txt
          if-no-files-found: error
