# This is the pipeline that will run nightly

name: Nightly

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '2 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Part_A_Tests:
    name: Part A Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TEST_FEATURE: [FeatureA, FeatureB, FeatureC, FeatureD, FeatureE, FeatureF]

    steps:
      - uses: actions/checkout@v3

      - name: ${{ matrix.TEST_FEATURE }}
        run: |
          cd part_a
          ./tests/run.sh ${{ matrix.TEST_FEATURE }} nightly | tee log.txt

      - name: Archive log
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: part_a/log.txt
          if-no-files-found: error

  Part_B_Tests:
    name: Part B Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TEST_FEATURE: [FeatureC, FeatureD, FeatureE, FeatureF, FeatureX, FeatureY, FeatureZ]
    
    steps:
      - uses: actions/checkout@v3

      - name: ${{ matrix.TEST_FEATURE }}
        run: |
          cd part_b
          ./tests/other_tests.sh ${{ matrix.TEST_FEATURE }} nightly | tee log.txt

      - name: Archive log
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: part_b/log.txt
          if-no-files-found: error
  
  Image_Tests:
    name: Image Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        TEST_TEAM: [TeamAlpha, TeamBravo, TeamTango]
        TEST_FEATURE: [FeatureA, FeatureB, FeatureF, FeatureX, FeatureY, FeatureZ]
        TEST_TYPE: [Type1, Type2, Type3]

    steps:
      - uses: actions/checkout@v3

      - name: ${{ matrix.TEST_TEAM }} ${{ matrix.TEST_FEATURE }} ${{ matrix.TEST_TYPE }}
        run: |
          cd image
          ./tests/test.sh ${{ matrix.TEST_FEATURE }} ${{ matrix.TEST_TEAM }} ${{ matrix.TEST_TYPE }} nightly | tee log.txt

      - name: Archive log
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: image/log.txt
          if-no-files-found: error
  
  Test_Report:
    name: Test Report
    runs-on: ubuntu-latest
    needs: [Part_A_Tests, Part_B_Tests]
    steps:
      - name: Generate test report
        run: echo Generating report >> report.html
      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.html
          if-no-files-found: error
